#!/usr/bin/env python

import utilities; from tkinter import Canvas, Tk; import helpers; import time; import random

def make_creature(canvas, center, size=100, tag='creature', fill='SteelBlue3'):
    left_eye_pos = (center[0] - size/1.2, center[1] - size / 4.5)
    right_eye_pos = (center[0] - size/1.8, center[1] - size / 4.5)
    eye_width = eye_height = size / 40
    left_large_eye_width = left_large_eye_height = size/8
    right_large_eye_width = right_large_eye_height = size/6.5
    utilities.make_line3(canvas,[
        (center[0]-size/0.7,center[1]-size/3),(center[0]-size,center[1]-size/0.8),(center[0]-size/1.6,center[1]-size/3)
    ],curvy=True,width=1.5,fill='White',tag=tag)
    utilities.make_oval(canvas, (center[0]-size/0.7,center[1]-size/3), size*0.3,size*0.3, color='orange', tag=tag,outline='orange')
    utilities.make_oval(canvas, (center[0]-size/0.7,center[1]-size/3), size*0.15,size*0.15, color='gold2', tag=tag,outline='gold2')
    utilities.make_oval(canvas, (center[0]-size/0.7,center[1]-size/3), size*0.1,size*0.1, color='yellow', tag=tag,outline='yellow')
    utilities.make_rectangle(canvas,(center[0]-size/4,center[1]-size/1.5),width=size*1.1,height=size/1.6,color='indianred3',tag=tag)
    utilities.make_rectangle(canvas,(center[0]-size/4,center[1]+size/5),width=size*1.1,height=size*0.5,color='indianred3',tag=tag)
    utilities.make_rectangle(canvas,(center[0]+size*1.1,center[1]-size*0.6),width=size*0.8,height=size*0.5,color='indianred3',tag=tag)
    utilities.make_rectangle(canvas,(center[0]+size*1.1,center[1]),width=size*0.8,height=size*0.5,color='indianred3',tag=tag)
    utilities.make_line(canvas,[(center[0]+size/2,center[1]-size/1.5),(center[0]+size/2,center[1]+size/1.44)],curvy=False,width=1.5,tag=tag)
    utilities.make_rectangle(canvas,(center[0]+size*1.1,center[1]),width=size*0.85,height=size*0.08,color='indianred4',tag=tag)
    utilities.make_rectangle(canvas,(center[0]+size*1.1,center[1]-size*0.1),width=size*0.85,height=size*0.08,color='indianred4',tag=tag)
    utilities.make_oval(canvas, center, size*1.15,size*0.6, color=fill, tag=tag,outline=fill)
    utilities.make_oval(canvas, left_eye_pos, left_large_eye_width, left_large_eye_height, color='white', tag=tag)
    utilities.make_oval(canvas, right_eye_pos, right_large_eye_width, right_large_eye_height, color='white', tag=tag)
    utilities.make_rectangle(canvas,(center[0]-size/0.8,center[1]+size/15),width=size/4.5,height=size/4.5,color='white',tag=tag)
    utilities.make_rectangle(canvas,(center[0]-size/1.1,center[1]+size/15),width=size/4.5,height=size/4.5,color='white',tag=tag)
    utilities.make_line(canvas,[(center[0]-size/5,center[1]+size/4.2),(center[0]-size/5,center[1]-size/4.2)],curvy=False,width=1.5,tag=tag)
    utilities.make_line(canvas,[(center[0]-size/8,center[1]+size/6),(center[0]-size/8,center[1]-size/6)],curvy=False,width=1.5,tag=tag)
    utilities.make_line(canvas,[(center[0],center[1]+size/12),(center[0],center[1]-size/12)],curvy=False,width=1.5,tag=tag)
    utilities.make_oval(canvas, left_eye_pos, eye_width, eye_height, color='black', tag=tag)
    utilities.make_oval(canvas, right_eye_pos, eye_width ,eye_height, color='black', tag=tag)
    utilities.make_line(canvas,[((center[0] - size/1.3) - size/4,center[1]-size/2.5),((center[0] - size/1.36) - size/6,center[1]-size/2),((center[0] - size/1.42),center[1]-size/2.5)],curvy=True,width=1.75,tag=tag)
    utilities.make_line(canvas,[(center[0] - size/1.5,center[1]-size/2.2),(center[0] - size/1.8+size/4,center[1]-size/2.2)],curvy=False,width=1.75,tag=tag)
    utilities.make_line(canvas,[(center[0]-size/0.75,center[1]+size/15),(center[0]-size/3.5,center[1]+size/15)],curvy=False,width=1.5,tag=tag)

def make_jellyfish(canvas, center, size=100, tag='jellyfish', fill='violetred2'):
    utilities.make_oval(canvas, (center[0]+size/0.7,center[1]-size/3), size*0.7,size*0.65, color=fill, tag=tag,outline=fill)
    utilities.make_rectangle(canvas,(center[0]+size/1.35,center[1]-size/6),width=size*1.38,height=size*0.5,color=fill,tag=tag)
    utilities.make_oval(canvas,(center[0]+size/0.73,center[1]-size/2),size/3,size/3,color='white',outline='black',tag=tag)
    utilities.make_oval(canvas,(center[0]+size/0.73,center[1]-size/2),size/20,size/20,color='black',outline='black',tag=tag)
    utilities.make_line2(canvas,[(center[0]+size/0.54,center[1]+size/1.75),(center[0]+size/0.4,center[1]+size/0.7),(center[0]+size/0.54,center[1]+size/0.6)],curvy=True,width=size*0.1,fill='VioetRed2',tag=tag)
    utilities.make_line2(canvas,[(center[0]+size/0.53,center[1]+size/0.61),(center[0]+size/0.68,center[1]+size/0.5),(center[0]+size/0.45,center[1]+size/0.4)],curvy=True,width=size*0.1,fill='VioletRed2',tag=tag)
    utilities.make_line4(canvas,[(center[0]+size/0.54,center[1]+size/1.75),(center[0]+size/0.4,center[1]+size/0.7),(center[0]+size/0.54,center[1]+size/0.6)],curvy=True,width=size*0.01,fill='Yellow',tag=tag)
    utilities.make_line4(canvas,[(center[0]+size/0.53,center[1]+size/0.61),(center[0]+size/0.68,center[1]+size/0.5),(center[0]+size/0.45,center[1]+size/0.4)],curvy=True,width=size*0.01,fill='Yellow',tag=tag)
    utilities.make_oval(canvas,(center[0]+size/0.45,center[1]+size/0.4),size*0.2,size*0.2,color='orange',outline='orange',tag=tag)
    utilities.make_oval(canvas,(center[0]+size/0.45,center[1]+size/0.4),size*0.1,size*0.1,color='gold2',outline='gold2',tag=tag)
    utilities.make_oval(canvas,(center[0]+size/0.45,center[1]+size/0.4),size*0.07,size*0.07,color='Yellow',outline='Yellow',tag=tag)

    utilities.make_line2(canvas,[(center[0]+size,center[1]+size/1.75),(center[0]+size/0.65,center[1]+size/0.7),(center[0]+size/1.02,center[1]+size/0.6)],curvy=True,width=size*0.1,fill='VioetRed2',tag=tag)
    utilities.make_line2(canvas,[(center[0]+size/0.98,center[1]+size/0.61),(center[0]+size/2,center[1]+size/0.5),(center[0]+size/0.98,center[1]+size/0.4)],curvy=True,width=size*0.1,fill='VioletRed2',tag=tag)
    utilities.make_line4(canvas,[(center[0]+size,center[1]+size/1.75),(center[0]+size/0.65,center[1]+size/0.7),(center[0]+size/1.02,center[1]+size/0.6)],curvy=True,width=size*0.01,fill='Yellow',tag=tag)
    utilities.make_line4(canvas,[(center[0]+size/0.98,center[1]+size/0.61),(center[0]+size/2,center[1]+size/0.5),(center[0]+size/0.98,center[1]+size/0.4)],curvy=True,width=size*0.01,fill='Yellow',tag=tag)
    utilities.make_oval(canvas,(center[0]+size/0.98,center[1]+size/0.4),size*0.2,size*0.2,color='orange',outline='orange',tag=tag)
    utilities.make_oval(canvas,(center[0]+size/0.98,center[1]+size/0.4),size*0.1,size*0.1,color='gold2',outline='gold2',tag=tag)
    utilities.make_oval(canvas,(center[0]+size/0.98,center[1]+size/0.4),size*0.07,size*0.07,color='Yellow',outline='Yellow',tag=tag)

    utilities.make_line2(canvas,[(center[0]+size/0.7,center[1]+size/1.75),(center[0]+size/0.5,center[1]+size/0.7),(center[0]+size/0.702,center[1]+size/0.6)],curvy=True,width=size*0.1,fill='VioetRed2',tag=tag)
    utilities.make_line2(canvas,[(center[0]+size/0.68,center[1]+size/0.61),(center[0]+size,center[1]+size/0.5),(center[0]+size/0.68,center[1]+size/0.4)],curvy=True,width=size*0.1,fill='VioletRed2',tag=tag)
    utilities.make_line4(canvas,[(center[0]+size/0.7,center[1]+size/1.75),(center[0]+size/0.5,center[1]+size/0.7),(center[0]+size/0.702,center[1]+size/0.6)],curvy=True,width=size*0.005,fill='Yellow',tag=tag)
    utilities.make_line4(canvas,[(center[0]+size/0.68,center[1]+size/0.61),(center[0]+size,center[1]+size/0.5),(center[0]+size/0.68,center[1]+size/0.4)],curvy=True,width=size*0.005,fill='Yellow',tag=tag)
    utilities.make_oval(canvas,(center[0]+size/0.68,center[1]+size/0.4),size*0.2,size*0.2,color='orange',outline='orange',tag=tag)
    utilities.make_oval(canvas,(center[0]+size/0.68,center[1]+size/0.4),size*0.1,size*0.1,color='gold2',outline='gold2',tag=tag)
    utilities.make_oval(canvas,(center[0]+size/0.68,center[1]+size/0.4),size*0.07,size*0.07,color='Yellow',outline='Yellow',tag=tag)

    utilities.make_oval(canvas, (center[0]+size/0.7,center[1]+size/3), size*0.25,size*0.3, color=fill, tag=tag,outline=fill)
    utilities.make_oval(canvas, (center[0]+size,center[1]+size/3), size*0.25,size*0.3, color=fill, tag=tag,outline=fill)
    utilities.make_oval(canvas, (center[0]+size/0.54,center[1]+size/3), size*0.25,size*0.3, color=fill, tag=tag,outline=fill)
    utilities.make_line(canvas,[(center[0]+size/0.6,center[1]-size/1.15),(center[0]+size/0.9,center[1]-size/1.15)],curvy=False,width=1.5,tag=tag)
    utilities.make_rectangle(canvas,(center[0]+size/0.7,center[1]-size/15),size*0.2,size*0.2,color='White',tag=tag)
    utilities.make_line(canvas,[
        (center[0]+size/1.1,center[1]-size/200),
        (center[0]+size/0.7,center[1]-size/8),
        (center[0]+size/0.5,center[1]-size/200)],curvy=True,width=2,tag=tag
    )

def make_blobfish(canvas, center, size=100, tag='creature', fill='orchid1'):
    utilities.make_rectangle(canvas,[center[0]-size/0.7,center[1]-size*0.3],width=size*2.9,height=size*0.6,color='orchid3',outline='orchid3',tag=tag)
    utilities.make_rectangle(canvas,(center[0]-size/0.7,center[1]),width=size*2.9,height=size*0.02,color='yellow',outline='yellow',tag=tag)
    utilities.make_oval(canvas,(center[0],center[1]),size*1.1,size*0.6,color=fill,outline=fill,tag=tag)
    utilities.make_oval(canvas,(center[0],center[1]-size/4),size*0.9,size*0.8,color=fill,outline=fill,tag=tag)
    utilities.make_oval(canvas,(center[0],center[1]+size/6),size*0.5,size*0.2,color='orchid3',outline='orchid3',tag=tag)
    utilities.make_rectangle(canvas,(center[0]-size/5,center[1]+size/11),width=size*0.2,height=size*0.09,color='White',tag=tag)
    utilities.make_rectangle(canvas,(center[0]+size/10,center[1]+size/11),width=size*0.2,height=size*0.09,color='White',tag=tag)
    utilities.make_line(canvas,[
        (center[0]-size/2.5,center[1]+size/5),
        (center[0],center[1]+size/6),
        (center[0]+size/2.5,center[1]+size/5)],curvy=True,width=2,tag=tag)
    utilities.make_line(canvas,[
        (center[0]-size/1.5,center[1]-size/2.2),
        (center[0]-size/2.5,center[1]-size),
        (center[0]-size/4,center[1]-size/2.2)],curvy=True,width=2,tag=tag)
    utilities.make_line(canvas,[
        (center[0]+size/1.5,center[1]-size/2.2),
        (center[0]+size/2.5,center[1]-size),
        (center[0]+size/4,center[1]-size/2.2)],curvy=True,width=2,tag=tag)
    utilities.make_oval(canvas,(center[0]+size/2.3,center[1]-size/2),size/10,size/10,color='White',outline='Black',tag=tag)
    utilities.make_oval(canvas,(center[0]-size/2.3,center[1]-size/2),size/10,size/10,color='White',outline='Black',tag=tag)
    utilities.make_oval(canvas,(center[0]+size/2.3,center[1]-size/2),size/35,size/35, color='Black',tag=tag)
    utilities.make_oval(canvas,(center[0]-size/2.3,center[1]-size/2),size/35,size/35,color='Black',tag=tag)
    utilities.make_line(canvas,[
        (center[0],center[1]-size*0.8),
        (center[0]-size/4,center[1]-size*0.05),
        (center[0]+size/4,center[1]-size*0.1)],curvy=True,width=2,tag=tag)
    utilities.make_oval(canvas,(center[0]-size/0.7,center[1]),size*0.15,size*0.5,color='Orange',outline='Orange',tag=tag)
    utilities.make_oval(canvas,(center[0]-size/0.7,center[1]),size*0.10,size*0.35,color='gold3',outline='gold3',tag=tag)
    utilities.make_oval(canvas,(center[0]-size/0.7,center[1]),size*0.05,size*0.2,color='Yellow',outline='Yellow',tag=tag)
    utilities.make_oval(canvas,(center[0]-size/0.7+size*2.9,center[1]),size*0.15,size*0.5,color='Orange',outline='Orange',tag=tag)
    utilities.make_oval(canvas,(center[0]-size/0.7+size*2.9,center[1]),size*0.10,size*0.35,color='gold3',outline='gold3',tag=tag)
    utilities.make_oval(canvas,(center[0]-size/0.7+size*2.9,center[1]),size*0.05,size*0.2,color='Yellow',outline='Yellow',tag=tag)
    utilities.make_oval(canvas,(center[0]-size/0.7+size*2.9,center[1]),size*0.05,size*0.2,color='Orange',outline='Orange',tag=tag)

def make_flooring(canvas, center, size=100, tag='creature', fill='dark slate gray',outline='forest green'):
    utilities.make_rectangle(canvas,(center[0]-size/0.2,center[1]+2*size),1000,100,color=fill)

def make_stationaryplants(canvas,center,size=100,tag='stationaryplants',fill='dark green', outline='dark green'):
    utilities.make_oval(canvas,(center[0],center[1]),size*0.1,size*0.5,color=fill,outline=fill,tag=tag)
    utilities.make_oval(canvas,(center[0],center[1]),size*0.4,size*0.05,color=fill,outline=fill,tag=tag)
    utilities.make_oval(canvas,(center[0],center[1]),size*0.3,size*0.03,color=fill,outline=fill,tag=tag)
    utilities.make_oval(canvas,(center[0],center[1]),size*0.3,size*0.03,color=fill,outline=fill,tag=tag)

def make_landscape_object(canvas,center,size=100,tag=None,fill='dark slate gray', outline='cyan4'):
    x = random.randint(1,9)
    i = 0
    for i in range(x):
        if i % 2 == 0:
            utilities.make_oval(canvas,(center[0],center[1]-(2*i*size/5)),size/15,size/5,color=fill,outline='cyan4')
        else:
            utilities.make_oval(canvas,(center[0],center[1]-(2*i*size/5)),size/15,size/5,color='cyan4',outline='dark slate gray')
    
import random
diameter = random.randint(1,9)/10

def make_bubble(canvas, center, diameter, outline='powder blue', tag= 'bubble', stroke_width=1, **kwargs):
    diameter = random.randint(1,9)/10
    for bubble in range(100):
        x = random.randint(0,1000)
        y = random.randint(0,1000)
        center = (x,y)
        diameter = random.randint(1,100)/3
        utilities.make_bubble(canvas, center, diameter,tag='bubble'+str(bubble))

def make_bubble2(canvas, center, diameter, outline='steelblue', tag=None, stroke_width=1, **kwargs):
    diameter = random.randint(1,9)/10
    for bubble in range(100):
        x = random.randint(0,1000)
        y = random.randint(0,1000)
        center = (x,y)
        diameter = random.randint(1,100)/3
        utilities.make_bubble2(canvas, center, diameter,tag='bubble2'+str(bubble))

def make_sparkles(canvas, center, size=5, tag='sparkles', fill='cornsilk2',outline="cornsilk2"):
    for sparkle in range(30):
        x = random.randint(0,1000)
        y = random.randint(0,900)
        center = (x,y)
        utilities.make_oval(canvas,center,size*0.1,size*1.2,color=fill,outline=fill,tag=tag)
        utilities.make_oval(canvas,center,size*0.8,size*0.1,color=fill,outline=fill,tag=tag)

def make_sparkles_from_click(canvas,event):
    helpers.make_sparkles(
        canvas,
        (event.x, event.y),
        random.uniform(40, 150), # random width
        fill='white',outline="cornsilk2"
    )

def make_babyjellyfish(canvas, center, size=100, tag='jellyfish', fill='violetred2'):
    utilities.make_oval(canvas, (center[0]+size/0.7,center[1]-size/3), size*0.7,size*0.65, color=fill, tag=tag,outline=fill)
    utilities.make_line2(canvas,[(center[0]+size/0.54,center[1]+size/1.75),(center[0]+size/0.4,center[1]+size/0.7),(center[0]+size/0.54,center[1]+size/0.6)],curvy=True,width=size*0.1,fill='VioetRed2',tag=tag)
    utilities.make_line2(canvas,[(center[0]+size/0.53,center[1]+size/0.61),(center[0]+size/0.68,center[1]+size/0.5),(center[0]+size/0.45,center[1]+size/0.4)],curvy=True,width=size*0.1,fill='VioletRed2',tag=tag)
    utilities.make_line4(canvas,[(center[0]+size/0.54,center[1]+size/1.75),(center[0]+size/0.4,center[1]+size/0.7),(center[0]+size/0.54,center[1]+size/0.6)],curvy=True,width=size*0.01,fill='Yellow',tag=tag)
    utilities.make_line4(canvas,[(center[0]+size/0.53,center[1]+size/0.61),(center[0]+size/0.68,center[1]+size/0.5),(center[0]+size/0.45,center[1]+size/0.4)],curvy=True,width=size*0.01,fill='Yellow',tag=tag)
    utilities.make_oval(canvas,(center[0]+size/0.45,center[1]+size/0.4),size*0.2,size*0.2,color='orange',outline='orange',tag=tag)
    utilities.make_oval(canvas,(center[0]+size/0.45,center[1]+size/0.4),size*0.1,size*0.1,color='gold2',outline='gold2',tag=tag)
    utilities.make_oval(canvas,(center[0]+size/0.45,center[1]+size/0.4),size*0.07,size*0.07,color='Yellow',outline='Yellow',tag=tag)

    utilities.make_line2(canvas,[(center[0]+size,center[1]+size/1.75),(center[0]+size/0.65,center[1]+size/0.7),(center[0]+size/1.02,center[1]+size/0.6)],curvy=True,width=size*0.1,fill='VioetRed2',tag=tag)
    utilities.make_line2(canvas,[(center[0]+size/0.98,center[1]+size/0.61),(center[0]+size/2,center[1]+size/0.5),(center[0]+size/0.98,center[1]+size/0.4)],curvy=True,width=size*0.1,fill='VioletRed2',tag=tag)
    utilities.make_line4(canvas,[(center[0]+size,center[1]+size/1.75),(center[0]+size/0.65,center[1]+size/0.7),(center[0]+size/1.02,center[1]+size/0.6)],curvy=True,width=size*0.01,fill='Yellow',tag=tag)
    utilities.make_line4(canvas,[(center[0]+size/0.98,center[1]+size/0.61),(center[0]+size/2,center[1]+size/0.5),(center[0]+size/0.98,center[1]+size/0.4)],curvy=True,width=size*0.01,fill='Yellow',tag=tag)
    utilities.make_oval(canvas,(center[0]+size/0.98,center[1]+size/0.4),size*0.2,size*0.2,color='orange',outline='orange',tag=tag)
    utilities.make_oval(canvas,(center[0]+size/0.98,center[1]+size/0.4),size*0.1,size*0.1,color='gold2',outline='gold2',tag=tag)
    utilities.make_oval(canvas,(center[0]+size/0.98,center[1]+size/0.4),size*0.07,size*0.07,color='Yellow',outline='Yellow',tag=tag)

    utilities.make_line2(canvas,[(center[0]+size/0.7,center[1]+size/1.75),(center[0]+size/0.5,center[1]+size/0.7),(center[0]+size/0.702,center[1]+size/0.6)],curvy=True,width=size*0.1,fill='VioetRed2',tag=tag)
    utilities.make_line2(canvas,[(center[0]+size/0.68,center[1]+size/0.61),(center[0]+size,center[1]+size/0.5),(center[0]+size/0.68,center[1]+size/0.4)],curvy=True,width=size*0.1,fill='VioletRed2',tag=tag)
    utilities.make_line4(canvas,[(center[0]+size/0.7,center[1]+size/1.75),(center[0]+size/0.5,center[1]+size/0.7),(center[0]+size/0.702,center[1]+size/0.6)],curvy=True,width=size*0.005,fill='Yellow',tag=tag)
    utilities.make_line4(canvas,[(center[0]+size/0.68,center[1]+size/0.61),(center[0]+size,center[1]+size/0.5),(center[0]+size/0.68,center[1]+size/0.4)],curvy=True,width=size*0.005,fill='Yellow',tag=tag)
    utilities.make_oval(canvas,(center[0]+size/0.68,center[1]+size/0.4),size*0.2,size*0.2,color='orange',outline='orange',tag=tag)
    utilities.make_oval(canvas,(center[0]+size/0.68,center[1]+size/0.4),size*0.1,size*0.1,color='gold2',outline='gold2',tag=tag)
    utilities.make_oval(canvas,(center[0]+size/0.68,center[1]+size/0.4),size*0.07,size*0.07,color='Yellow',outline='Yellow',tag=tag)

    utilities.make_oval(canvas, (center[0]+size/0.7,center[1]+size/3), size*0.25,size*0.3, color=fill, tag=tag,outline=fill)
    utilities.make_oval(canvas, (center[0]+size,center[1]+size/3), size*0.25,size*0.3, color=fill, tag=tag,outline=fill)
    utilities.make_oval(canvas, (center[0]+size/0.54,center[1]+size/3), size*0.25,size*0.3, color=fill, tag=tag,outline=fill)
